pull_request_rules:
  - name: automatic merge repomanager
    conditions:
      - author=the-repository-manager[bot]
    actions:
      merge:
        method: rebase
        rebase_fallback: squash
  - name: assign to owner
    conditions:
      - check-failure>1
    actions:
      assign:
        users:
          - chrisns
