apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: passman
spec:
  version: {{ .TagName }}
  platforms:

  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/chrisns/kubectl-passman/releases/download/{{ .TagName }}/kubectl-passman-darwin-arm64.zip" .TagName }}
    bin: "./kubectl-passman"
    files:
      - from: kubectl-passman-darwin-arm64
        to: kubectl-passman
      - from: LICENSE
        to: .

  - selector:
      matchLabels:
        os: linux
        arch: arm
    {{addURIAndSha "https://github.com/chrisns/kubectl-passman/releases/download/{{ .TagName }}/kubectl-passman-linux-arm.zip" .TagName }}
    bin: "./kubectl-passman"
    files:
      - from: kubectl-passman-linux-arm
        to: kubectl-passman
      - from: LICENSE
        to: .

  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/chrisns/kubectl-passman/releases/download/{{ .TagName }}/kubectl-passman-linux-arm64.zip" .TagName }}
    bin: "./kubectl-passman"
    files:
      - from: kubectl-passman-linux-arm64
        to: kubectl-passman
      - from: LICENSE
        to: .

  - selector:
      matchLabels:
        os: linux
        arch: 386
    {{addURIAndSha "https://github.com/chrisns/kubectl-passman/releases/download/{{ .TagName }}/kubectl-passman-linux-386.zip" .TagName }}
    bin: "./kubectl-passman"
    files:
      - from: kubectl-passman-linux-386
        to: kubectl-passman
      - from: LICENSE
        to: .

  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/chrisns/kubectl-passman/releases/download/{{ .TagName }}/kubectl-passman-linux-amd64.zip" .TagName }}
    bin: "./kubectl-passman"
    files:
      - from: kubectl-passman-linux-amd64
        to: kubectl-passman
      - from: LICENSE
        to: .

  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/chrisns/kubectl-passman/releases/download/{{ .TagName }}/kubectl-passman-windows-amd64.zip" .TagName }}
    bin: "./kubectl-passman.exe"
    files:
      - from: kubectl-passman-windows-amd64.exe
        to: kubectl-passman.exe
      - from: LICENSE
        to: .

  - selector:
      matchLabels:
        os: windows
        arch: 386
    {{addURIAndSha "https://github.com/chrisns/kubectl-passman/releases/download/{{ .TagName }}/kubectl-passman-windows-386.zip" .TagName }}
    bin: "./kubectl-passman.exe"
    files:
      - from: kubectl-passman-windows-386.exe
        to: kubectl-passman.exe
      - from: LICENSE
        to: .


  shortDescription: Store kubeconfig credentials in keychains or password managers
  homepage: https://github.com/chrisns/kubectl-passman
  caveats: |
    This plugin needs a usable keychain or password manager
    See usage docs https://github.com/chrisns/kubectl-passman
  description: |
    An effective way to keep your credentials somewhere better than in plain text
